In [16]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

#scores:ndarray | None = None # 學生的分數
#scores_df:DataFrame | None = None # 學生分數的DataFrame

scores:ndarray = np.random.randint(40, 101, size=(50, 5))
scores_df:DataFrame = pd.DataFrame(scores,            
            columns=['國文', '英文', '數學', '地理', '歷史'],
            index=range(1,51))

names_df:DataFrame = pd.read_csv('students.csv')
scores_df[['姓名','性別']] = names_df[['姓名','性別']].head(n=50).values
scores_df = scores_df[['姓名', '性別','國文', '英文', '數學', '地理', '歷史']]
#選取欄
scores_df[['姓名','國文']]
#選取列
scores_df.iloc[5]
scores_df.iloc[5:10]

     姓名 性別  國文  英文  數學  地理  歷史
6   朱冠霖  男  61  53  72  91  88
7   謝欣蓉  女  68  54  53  86  64
8   羅淑芬  女  90  54  67  66  97
9   許美慧  女  64  94  85  87  80
10  廖志豪  男  85  46  56  71  60

In [17]:
scores_df[scores_df['姓名'] == '許美慧']
scores_df[scores_df['國文'] < 60]
scores_df.query("性別 == '女' and 國文 < 60 ")

     姓名 性別  國文  英文  數學  地理  歷史
15  王婉茹  女  50  66  92  55  77
24  呂佳瑩  女  43  64  48  58  60
25  洪怡君  女  57  78  97  63  45
28  郭怡萱  女  52  66  83  90  81
29  簡婉慧  女  44  74  55  43  93
30  楊靜宜  女  50  91  85  97  60
39  彭美慧  女  55  79  59  67  53
47  周美玲  女  48  73  67  85  85

In [18]:
scores_df["總分"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].sum(axis=1)
scores_df["平均"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].mean(axis=1)
scores_df["排名"] = scores_df["總分"].rank(ascending=False,method='min')
scores_df.sort_values(by='排名')

     姓名 性別  國文   英文  數學   地理  歷史   總分    平均    排名
4   蕭志明  男  78   89  97   94  99  457  91.4   1.0
27  江雅琪  女  94   93  64   86  96  433  86.6   2.0
43  吳雅萍  女  85   78  84  100  85  432  86.4   3.0
49  曾明哲  男  81   61  90   98  99  429  85.8   4.0
42  邱裕豪  男  96   90  51   88  92  417  83.4   5.0
9   許美慧  女  64   94  85   87  80  410  82.0   6.0
2   曾彥廷  男  87   90  91   94  47  409  81.8   7.0
13  蘇雅婷  女  77  100  66   98  62  403  80.6   8.0
36  蕭浩宇  男  74   93  56   81  93  397  79.4   9.0
41  許淑芬  女  67   96  46   86  96  391  78.2  10.0
37  呂怡靜  女  91   64  57   89  86  387  77.4  11.0
34  簡建宏  男  81   48  76   99  80  384  76.8  12.0
30  楊靜宜  女  50   91  85   97  60  383  76.6  13.0
3   吳子睿  男  53   83  90   88  66  380  76.0  14.0
11  葉柏翰  男  93   75  62   48  98  376  75.2  15.0
32  蕭怡伶  女  87   64  91   57  76  375  75.0  16.0
8   羅淑芬  女  90   54  67   66  97  374  74.8  17.0
28  郭怡萱  女  52   66  83   90  81  372  74.4  18.0
12  呂承恩  男  59   85  41   85  99  369  73.8  19.0
38  邱宗翰  男  82   89  73   67  57  368  73.6  20.0
19  呂婉慧  女  89   95  51   87  46  368  73.6  20.0
50  詹柏翰  男  83   45  86   70  83  367  73.4  22.0
6   朱冠霖  男  61   53  72   91  88  365  73.0  23.0
46  鍾浩銘  男  59   52  75   84  93  363  72.6  24.0
33  洪裕豪  男  80   74  68   48  92  362  72.4  25.0
47  周美玲  女  48   73  67   85  85  358  71.6  26.0
1   劉彥宏  男  57   80  94   74  52  357  71.4  27.0
5   王文傑  男  62   59  67   71  87  346  69.2  28.0
18  王冠廷  男  84   65  72   66  58  345  69.0  29.0
40  劉靜芬  女  76   53  68   99  47  343  68.6  30.0
21  蘇彥宏  男  88   91  48   51  64  342  68.4  31.0
15  王婉茹  女  50   66  92   55  77  340  68.0  32.0
25  洪怡君  女  57   78  97   63  45  340  68.0  32.0
17  黃裕傑  男  65   53  83   44  94  339  67.8  34.0
26  洪柏宏  男  56   63  80   51  88  338  67.6  35.0
20  莊子謙  男  98   49  44   52  91  334  66.8  36.0
14  高浩宇  男  72   75  60   64  55  326  65.2  37.0
7   謝欣蓉  女  68   54  53   86  64  325  65.0  38.0
45  莊柏融  男  54   69  62   70  66  321  64.2  39.0
10  廖志豪  男  85   46  56   71  60  318  63.6  40.0
16  莊承翰  男  63   66  51   86  49  315  63.0  41.0
39  彭美慧  女  55   79  59   67  53  313  62.6  42.0
29  簡婉慧  女  44   74  55   43  93  309  61.8  43.0
35  劉浩然  男  75   50  48   69  65  307  61.4  44.0
31  曾靜儀  女  95   44  54   65  46  304  60.8  45.0
48  劉婉婷  女  62   57  54   75  46  294  58.8  46.0
44  施子軒  男  77   69  58   47  41  292  58.4  47.0
23  曾明軒  男  43   60  51   70  58  282  56.4  48.0
24  呂佳瑩  女  43   64  48   58  60  273  54.6  49.0
22  李柏融  男  43   62  46   53  42  246  49.2  50.0

In [19]:
def get_failing_subjects(row):
    subjects = ['國文', '英文', '數學', '地理', '歷史']
    failing = [subj for subj in subjects if row[subj] < 60]    
    return ','.join(failing) if failing else "無"
    
    
scores_df["不及格的科目名稱"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].apply(get_failing_subjects,axis=1)
scores_df

     姓名 性別  國文   英文  數學   地理  歷史   總分    平均    排名     不及格的科目名稱
1   劉彥宏  男  57   80  94   74  52  357  71.4  27.0        國文,歷史
2   曾彥廷  男  87   90  91   94  47  409  81.8   7.0           歷史
3   吳子睿  男  53   83  90   88  66  380  76.0  14.0           國文
4   蕭志明  男  78   89  97   94  99  457  91.4   1.0            無
5   王文傑  男  62   59  67   71  87  346  69.2  28.0           英文
6   朱冠霖  男  61   53  72   91  88  365  73.0  23.0           英文
7   謝欣蓉  女  68   54  53   86  64  325  65.0  38.0        英文,數學
8   羅淑芬  女  90   54  67   66  97  374  74.8  17.0           英文
9   許美慧  女  64   94  85   87  80  410  82.0   6.0            無
10  廖志豪  男  85   46  56   71  60  318  63.6  40.0        英文,數學
11  葉柏翰  男  93   75  62   48  98  376  75.2  15.0           地理
12  呂承恩  男  59   85  41   85  99  369  73.8  19.0        國文,數學
13  蘇雅婷  女  77  100  66   98  62  403  80.6   8.0            無
14  高浩宇  男  72   75  60   64  55  326  65.2  37.0           歷史
15  王婉茹  女  50   66  92   55  77  340  68.0  32.0        國文,地理
16  莊承翰  男  63   66  51   86  49  315  63.0  41.0        數學,歷史
17  黃裕傑  男  65   53  83   44  94  339  67.8  34.0        英文,地理
18  王冠廷  男  84   65  72   66  58  345  69.0  29.0           歷史
19  呂婉慧  女  89   95  51   87  46  368  73.6  20.0        數學,歷史
20  莊子謙  男  98   49  44   52  91  334  66.8  36.0     英文,數學,地理
21  蘇彥宏  男  88   91  48   51  64  342  68.4  31.0        數學,地理
22  李柏融  男  43   62  46   53  42  246  49.2  50.0  國文,數學,地理,歷史
23  曾明軒  男  43   60  51   70  58  282  56.4  48.0     國文,數學,歷史
24  呂佳瑩  女  43   64  48   58  60  273  54.6  49.0     國文,數學,地理
25  洪怡君  女  57   78  97   63  45  340  68.0  32.0        國文,歷史
26  洪柏宏  男  56   63  80   51  88  338  67.6  35.0        國文,地理
27  江雅琪  女  94   93  64   86  96  433  86.6   2.0            無
28  郭怡萱  女  52   66  83   90  81  372  74.4  18.0           國文
29  簡婉慧  女  44   74  55   43  93  309  61.8  43.0     國文,數學,地理
30  楊靜宜  女  50   91  85   97  60  383  76.6  13.0           國文
31  曾靜儀  女  95   44  54   65  46  304  60.8  45.0     英文,數學,歷史
32  蕭怡伶  女  87   64  91   57  76  375  75.0  16.0           地理
33  洪裕豪  男  80   74  68   48  92  362  72.4  25.0           地理
34  簡建宏  男  81   48  76   99  80  384  76.8  12.0           英文
35  劉浩然  男  75   50  48   69  65  307  61.4  44.0        英文,數學
36  蕭浩宇  男  74   93  56   81  93  397  79.4   9.0           數學
37  呂怡靜  女  91   64  57   89  86  387  77.4  11.0           數學
38  邱宗翰  男  82   89  73   67  57  368  73.6  20.0           歷史
39  彭美慧  女  55   79  59   67  53  313  62.6  42.0     國文,數學,歷史
40  劉靜芬  女  76   53  68   99  47  343  68.6  30.0        英文,歷史
41  許淑芬  女  67   96  46   86  96  391  78.2  10.0           數學
42  邱裕豪  男  96   90  51   88  92  417  83.4   5.0           數學
43  吳雅萍  女  85   78  84  100  85  432  86.4   3.0            無
44  施子軒  男  77   69  58   47  41  292  58.4  47.0     數學,地理,歷史
45  莊柏融  男  54   69  62   70  66  321  64.2  39.0           國文
46  鍾浩銘  男  59   52  75   84  93  363  72.6  24.0        國文,英文
47  周美玲  女  48   73  67   85  85  358  71.6  26.0           國文
48  劉婉婷  女  62   57  54   75  46  294  58.8  46.0     英文,數學,歷史
49  曾明哲  男  81   61  90   98  99  429  85.8   4.0            無
50  詹柏翰  男  83   45  86   70  83  367  73.4  22.0           英文