In [1]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

#scores:ndarray | None = None # 學生的分數
#scores_df:DataFrame | None = None # 學生分數的DataFrame

scores:ndarray = np.random.randint(40, 101, size=(50, 5))
scores_df:DataFrame = pd.DataFrame(scores,            
            columns=['國文', '英文', '數學', '地理', '歷史'],
            index=range(1,51))

names_df:DataFrame = pd.read_csv('students.csv')
scores_df[['姓名','性別']] = names_df[['姓名','性別']].head(n=50).values
scores_df = scores_df[['姓名', '性別','國文', '英文', '數學', '地理', '歷史']]
#選取欄
scores_df[['姓名','國文']]
#選取列
scores_df.iloc[5]
scores_df.iloc[5:10]

     姓名 性別  國文  英文  數學  地理  歷史
6   朱冠霖  男  83  67  42  94  95
7   謝欣蓉  女  68  86  41  93  87
8   羅淑芬  女  67  99  91  73  85
9   許美慧  女  92  40  43  92  51
10  廖志豪  男  59  45  95  92  95

In [2]:
scores_df[scores_df['姓名'] == '許美慧']
scores_df[scores_df['國文'] < 60]

     姓名 性別  國文  英文   數學   地理  歷史
2   曾彥廷  男  44  42  100   92  81
10  廖志豪  男  59  45   95   92  95
12  呂承恩  男  48  97   51   50  83
13  蘇雅婷  女  45  73   67   99  71
16  莊承翰  男  40  59   62   90  55
20  莊子謙  男  59  72   67   80  92
23  曾明軒  男  54  45   85   48  97
25  洪怡君  女  59  52   68   47  58
26  洪柏宏  男  41  80   61   71  76
28  郭怡萱  女  50  49   75   46  41
30  楊靜宜  女  57  74   78   76  40
31  曾靜儀  女  46  82   84   64  75
33  洪裕豪  男  40  70   40   72  62
34  簡建宏  男  50  65   51   87  41
36  蕭浩宇  男  52  45   51   50  52
40  劉靜芬  女  46  68   69   80  46
41  許淑芬  女  40  51   88   57  94
42  邱裕豪  男  46  93   73   51  98
43  吳雅萍  女  45  88   69   67  90
44  施子軒  男  40  57   96  100  56
46  鍾浩銘  男  54  91   44   63  57
47  周美玲  女  40  55   80   57  82
48  劉婉婷  女  45  91   61   87  48
50  詹柏翰  男  56  47   75   48  63