In [1]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

scores:ndarray | None = None # 學生的分數
scores_df:DataFrame | None = None # 學生分數的DataFrame

scores = np.random.randint(40, 101, size=(50, 5))
scores_df = pd.DataFrame(scores,            
            columns=['國文', '英文', '數學', '地理', '歷史'],
            index=range(1,51))
##scores_df.T
names_df:DataFrame = pd.read_csv('students11.csv')
names_df['姓名'].head(n=50).values
scores_df[['姓名','性別']] = names_df[['姓名','性別']].head(n=50).values
scores_df = scores_df[['姓名', '性別', '國文', '英文', '數學', '地理', '歷史']]
scores_df

     姓名 性別   國文   英文   數學   地理   歷史
1   王大明  男   62   64   42   81   93
2   李小華  女   46   55   68   48   95
3   張志偉  男   91   47   44   99   84
4   陳美玲  女   60   84   58   72   47
5   林俊傑  男   93   58   59   95   80
6   黃雅婷  女   55   84   72   89   48
7   劉家豪  男   79   47   79   63   55
8   吳怡君  女   41   53   67   41   53
9   蔡宗翰  男   66   66   72   88   58
10  鄭雅涵  女   64   52   62   49   64
11  許智傑  男   77   95  100   53   49
12  謝佳穎  女   50   69   79   64   78
13  郭建宏  男   81   90   45   54   55
14  簡淑芬  女   75   63   87   63   40
15  曾彥翔  男   82   84   48   94   43
16  邱意晴  女   76   81   73   77   40
17  莊明軒  男   80   47   41   65   98
18  廖婉如  女   41   53   48   98   78
19  周子軒  男   78   90   69   48   70
20  葉芷涵  女   41   68   67   77   76
21  洪偉成  男   61   72   78   95   88
22  徐佳琳  女   95   78   63   54   44
23  賴俊宏  男   64   46   65   49   81
24  方淑惠  女   41   71   54   53   46
25  邬志豪  男   81   73   68   87   45
26  蘇芳儀  女   59   52   87   40   59
27  呂宗翰  男   55   43   46   65   71
28  盧怡君  女   81  100   92   59   41
29  何家瑞  男   40   55   89   95   45
30  江佩珊  女   84   72   63   66   50
31  羅志祥  男  100   45   99   57   51
32  詹雅雯  女   64   51   85  100   59
33  胡冠廷  男   93   84   90   87   52
34  潘佳穎  女   85   68   92   61   90
35  葉俊宏  男   92   95   83   72   44
36  趙心瑜  女   81   87   73   86   67
37  梁哲嘉  男   62   42   46   57   66
38  許芸慈  女   62   65   49   77   82
39  藍天佑  男   59   42   89   72   93
40  康芷瑄  女   58   87   42   88   92
41  范姜宏  男   91   63   77   92   75
42  宋宜芳  女   81   87   85   43   98
43  韓明哲  男   85   98   95   42   91
44  唐雨婷  女   55   65   43   49   54
45  蕭裕民  男   91   93   66   55   85
46  馮曉君  女   57   74   98   48   73
47  董育廷  男   55   49   86   87   54
48  程雅筑  女  100   43   53   64  100
49  曹志遠  男   49   97   52   77   57
50  鄧宜真  女   49   61   90   59   48

In [ ]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

scores:ndarray | None = None # 學生的分數
scores_df:DataFrame | None = None # 學生分數的DataFrame

scores = np.random.randint(40, 101, size=(50, 5))
scores_df = pd.DataFrame(scores,            
            columns=['國文', '英文', '數學', '地理', '歷史'],
            index=range(1,51))
##scores_df.T
names_df:DataFrame = pd.read_csv('students11.csv')
names_df['姓名'].head(n=50).values
scores_df[['姓名','性別']] = names_df[['姓名','性別']].head(n=50).values
scores_df = scores_df[['姓名', '性別', '國文', '英文', '數學', '地理', '歷史']]
#選取欄
scores_df[['姓名','國文']]
#選取列
scores_df.iloc[0:5]
#混合選取
scores_df.loc[5:10, ['姓名','國文']]

     姓名  國文
5   林俊傑  67
6   黃雅婷  73
7   劉家豪  49
8   吳怡君  88
9   蔡宗翰  91
10  鄭雅涵  77

In [3]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

#scores:ndarray | None = None # 學生的分數
#scores_df:DataFrame | None = None # 學生分數的DataFrame

scores:ndarray = np.random.randint(40, 101, size=(50, 5))
scores_df:DataFrame = pd.DataFrame(scores,            
            columns=['國文', '英文', '數學', '地理', '歷史'],
            index=range(1,51))
##scores_df.T
names_df:DataFrame = pd.read_csv('students11.csv')
names_df['姓名'].head(n=50).values
scores_df[['姓名','性別']] = names_df[['姓名','性別']].head(n=50).values
scores_df = scores_df[['姓名', '性別', '國文', '英文', '數學', '地理', '歷史']]

#搜尋值
scores_df[scores_df['姓名'] == '吳怡君']

    姓名 性別  國文  英文  數學  地理  歷史
8  吳怡君  女  41  72  64  60  99

In [4]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

#scores:ndarray | None = None # 學生的分數
#scores_df:DataFrame | None = None # 學生分數的DataFrame

scores:ndarray = np.random.randint(40, 101, size=(50, 5))
scores_df:DataFrame = pd.DataFrame(scores,            
            columns=['國文', '英文', '數學', '地理', '歷史'],
            index=range(1,51))
##scores_df.T
names_df:DataFrame = pd.read_csv('students11.csv')
names_df['姓名'].head(n=50).values
scores_df[['姓名','性別']] = names_df[['姓名','性別']].head(n=50).values
scores_df = scores_df[['姓名', '性別', '國文', '英文', '數學', '地理', '歷史']]

#搜尋值
scores_df[scores_df['國文'] < 60]

     姓名 性別  國文  英文  數學  地理   歷史
4   陳美玲  女  54  58  53  98   57
8   吳怡君  女  44  48  58  97  100
9   蔡宗翰  男  49  57  96  48   41
11  許智傑  男  42  62  67  89   68
12  謝佳穎  女  56  95  75  72   74
14  簡淑芬  女  44  68  58  94   50
19  周子軒  男  47  45  68  44   52
21  洪偉成  男  52  76  75  65   52
22  徐佳琳  女  51  77  93  79   53
25  邬志豪  男  56  62  97  73   71
26  蘇芳儀  女  49  62  94  58   92
27  呂宗翰  男  57  56  63  66   90
30  江佩珊  女  41  65  89  67   86
33  胡冠廷  男  56  79  71  64   70
34  潘佳穎  女  42  56  71  60   73
37  梁哲嘉  男  55  40  78  90   99
42  宋宜芳  女  58  90  43  63   79
47  董育廷  男  51  77  75  60   78

In [14]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

#scores:ndarray | None = None # 學生的分數
#scores_df:DataFrame | None = None # 學生分數的DataFrame

scores:ndarray = np.random.randint(40, 101, size=(50, 5))
scores_df:DataFrame = pd.DataFrame(scores,            
            columns=['國文', '英文', '數學', '地理', '歷史'],
            index=range(1,51))
##scores_df.T
names_df:DataFrame = pd.read_csv('students11.csv')
names_df['姓名'].head(n=50).values
scores_df[['姓名','性別']] = names_df[['姓名','性別']].head(n=50).values
scores_df = scores_df[['姓名', '性別', '國文', '英文', '數學', '地理', '歷史']]

#搜尋值
scores_df.query("性別 == '女' and 國文 < 60")

     姓名 性別  國文  英文  數學  地理  歷史
2   李小華  女  49  59  62  43  62
6   黃雅婷  女  46  55  89  44  96
14  簡淑芬  女  41  55  78  78  97
20  葉芷涵  女  57  61  41  59  94
42  宋宜芳  女  57  55  66  75  91

In [34]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

#scores:ndarray | None = None # 學生的分數
#scores_df:DataFrame | None = None # 學生分數的DataFrame

scores:ndarray = np.random.randint(40, 101, size=(50, 5))
scores_df:DataFrame = pd.DataFrame(scores,            
            columns=['國文', '英文', '數學', '地理', '歷史'],
            index=range(1,51))
##scores_df.T
names_df:DataFrame = pd.read_csv('students11.csv')
names_df['姓名'].head(n=50).values
scores_df[['姓名','性別']] = names_df[['姓名','性別']].head(n=50).values
scores_df = scores_df[['姓名', '性別', '國文', '英文', '數學', '地理', '歷史']]

#統計
scores_df['總分'] = scores_df[['國文', '英文', '數學', '地理', '歷史']].sum(axis=1)       # 加總
scores_df['平均'] = scores_df[['國文', '英文', '數學', '地理', '歷史']].mean(axis=1)       # 平均
scores_df['排名'] = scores_df[['總分']].rank(ascending=False,method='min')       # 排名
scores_df.sort_values(by='排名') #排序
scores_df

     姓名 性別   國文  英文  數學  地理   歷史   總分    平均    排名
1   王大明  男   79  65  50  40   77  311  62.2  44.0
2   李小華  女  100  45  69  46   52  312  62.4  42.0
3   張志偉  男   84  60  70  89   74  377  75.4   8.0
4   陳美玲  女   84  77  83  87   48  379  75.8   6.0
5   林俊傑  男   97  55  73  85   99  409  81.8   4.0
6   黃雅婷  女   44  78  92  54   75  343  68.6  24.0
7   劉家豪  男   59  83  70  75   41  328  65.6  33.0
8   吳怡君  女   87  69  57  42   85  340  68.0  26.0
9   蔡宗翰  男   86  76  59  57   89  367  73.4  11.0
10  鄭雅涵  女   84  44  98  44   66  336  67.2  28.0
11  許智傑  男  100  98  95  50   67  410  82.0   3.0
12  謝佳穎  女   99  61  57  53   62  332  66.4  30.0
13  郭建宏  男   49  97  54  56   58  314  62.8  38.0
14  簡淑芬  女   77  52  77  51   56  313  62.6  40.0
15  曾彥翔  男   58  81  91  51   64  345  69.0  21.0
16  邱意晴  女   76  42  51  98   47  314  62.8  38.0
17  莊明軒  男   60  63  53  52   91  319  63.8  36.0
18  廖婉如  女   58  62  92  43   56  311  62.2  44.0
19  周子軒  男   55  70  59  57   72  313  62.6  40.0
20  葉芷涵  女   62  52  87  45   63  309  61.8  47.0
21  洪偉成  男   84  79  86  54   63  366  73.2  13.0
22  徐佳琳  女   53  80  86  84   75  378  75.6   7.0
23  賴俊宏  男   97  51  98  65   74  385  77.0   5.0
24  方淑惠  女   97  68  53  59   85  362  72.4  14.0
25  邬志豪  男   96  87  43  42   78  346  69.2  20.0
26  蘇芳儀  女   85  81  72  81   53  372  74.4   9.0
27  呂宗翰  男   72  44  97  75   66  354  70.8  17.0
28  盧怡君  女   62  60  83  67   40  312  62.4  42.0
29  何家瑞  男   58  72  55  51   50  286  57.2  49.0
30  江佩珊  女   82  55  52  73   82  344  68.8  23.0
31  羅志祥  男   74  92  80  76   40  362  72.4  14.0
32  詹雅雯  女   81  51  54  65   87  338  67.6  27.0
33  胡冠廷  男   40  54  91  45   72  302  60.4  48.0
34  潘佳穎  女   61  94  62  51   77  345  69.0  21.0
35  葉俊宏  男   86  40  46  77   74  323  64.6  34.0
36  趙心瑜  女   47  92  43  41   42  265  53.0  50.0
37  梁哲嘉  男   92  74  54  51   97  368  73.6  10.0
38  許芸慈  女   51  69  67  67  100  354  70.8  17.0
39  藍天佑  男   71  84  86  43   63  347  69.4  19.0
40  康芷瑄  女   95  47  76  81   56  355  71.0  16.0
41  范姜宏  男   46  42  63  86   86  323  64.6  34.0
42  宋宜芳  女   61  60  92  46   51  310  62.0  46.0
43  韓明哲  男   95  92  51  52   41  331  66.2  32.0
44  唐雨婷  女   51  89  88  62   42  332  66.4  30.0
45  蕭裕民  男   85  48  95  72   42  342  68.4  25.0
46  馮曉君  女   59  69  44  62   81  315  63.0  37.0
47  董育廷  男   96  98  95  94   75  458  91.6   1.0
48  程雅筑  女   77  78  94  94   94  437  87.4   2.0
49  曹志遠  男   55  77  95  64   76  367  73.4  11.0
50  鄧宜真  女   92  80  67  54   42  335  67.0  29.0