In [2]:
import pandas as pd

df = pd.read_csv("考試分數_3年6班.csv")
search_name = df[df["學生姓名"] == "趙冠宇"]
print(search_name)

   學生姓名  語文  數學  英語  物理  化學
10  趙冠宇  85  82  88  84  86

In [14]:
import pandas as pd

df = pd.read_csv("考試分數_3年6班.csv")
df
#print(result)

   學生姓名  語文  數學  英語  物理  化學
0   王小明  85  92  78  88  90
1   李美芳  90  88  95  82  85
2   張家豪  75  80  70  72  78
3   陳建宏  82  85  80  85  88
4   林志強  68  72  65  70  60
5   黃淑惠  92  95  90  94  92
6   吳明憲  80  78  85  80  82
7   蔡佩珊  88  90  92  88  90
8   郭政達  72  75  68  70  72
9   楊佳琪  95  92  98  95  96
10  趙冠宇  85  82  88  84  86
11  許家榮  78  80  75  78  80
12  鄭雅文  90  92  88  90  92
13  謝承翰  82  84  80  82  84
14  洪婉婷  88  86  90  88  86
15  曾志翔  70  72  68  70  72
16  劉美玲  92  94  90  92  94
17  蘇俊宏  85  80  82  85  80
18  葉雅婷  94  96  92  94  96
19  莊凱翔  76  78  74  76  78
20  呂佩穎  88  90  86  88  90
21  何志龍  82  80  84  82  80
22  羅佳穎  90  88  92  90  88
23  高家豪  74  76  72  74  76
24  蕭淑芬  92  90  94  92  90
25  潘冠宏  80  82  78  80  82
26  田雅琪  88  86  90  88  86
27  馮志強  72  74  70  72  74
28  蔣美惠  95  92  98  95  92
29  曹家榮  84  86  82  84  86
30  魏佩珊  90  92  88  90  92
31  彭承翰  78  80  76  78  80
32  袁佳琪  92  94  90  92  94
33  盧志宏  82  84  80  82  84
34  鄧婉婷  88  86  90  88  86
35  范家豪  70  72  68  70  72
36  汪美玲  94  96  92  94  96
37  賈俊宏  86  84  88  86  84
38  陸雅婷  90  92  88  90  92
39  韓凱翔  74  76  72  74  76
40  尤佩穎  88  90  86  88  90
41  柏志龍  82  80  84  82  80
42  焦佳穎  92  90  94  92  90
43  舒家豪  76  78  74  76  78
44  屈淑芬  90  88  92  90  88
45  項冠宏  80  82  78  80  82
46  祝雅琪  88  86  90  88  86
47  董志強  72  74  70  72  74
48  梁美惠  95  92  98  95  92
49  范家榮  84  86  82  84  86

In [13]:
import pandas as pd

df = pd.read_csv("考試分數_3年6班.csv")
search_name = df[df["學生姓名"] == "趙冠宇"]
print(search_name)

   學生姓名  語文  數學  英語  物理  化學
10  趙冠宇  85  82  88  84  86

In [ ]:
#解說範例
import pandas as pd

df = pd.DataFrame({
    "學生姓名": ["王小明", "趙冠宇", "李小華", "趙冠宇"],
    "分數": [80, 95, 72, 88]
})

df[df["學生姓名"] == "趙冠宇"]

  學生姓名  分數
1  趙冠宇  95
3  趙冠宇  88

In [17]:
import pandas as pd

df = pd.read_csv("考試分數_3年6班.csv")
df[df["語文"] >= 90]

   學生姓名  語文  數學  英語  物理  化學
1   李美芳  90  88  95  82  85
5   黃淑惠  92  95  90  94  92
9   楊佳琪  95  92  98  95  96
12  鄭雅文  90  92  88  90  92
16  劉美玲  92  94  90  92  94
18  葉雅婷  94  96  92  94  96
22  羅佳穎  90  88  92  90  88
24  蕭淑芬  92  90  94  92  90
28  蔣美惠  95  92  98  95  92
30  魏佩珊  90  92  88  90  92
32  袁佳琪  92  94  90  92  94
36  汪美玲  94  96  92  94  96
38  陸雅婷  90  92  88  90  92
42  焦佳穎  92  90  94  92  90
44  屈淑芬  90  88  92  90  88
48  梁美惠  95  92  98  95  92