In [8]:
import pandas as pd

dataFrame = pd.read_csv('各鄉鎮市區人口密度.csv')
dataFrame.dtypes
len(dataFrame)
dataFrame.info()

<class 'pandas.DataFrame'>
RangeIndex: 376 entries, 0 to 375
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   statistic_yyy       371 non-null    str
 1   site_id             375 non-null    str
 2   people_total        371 non-null    str
 3   area                371 non-null    str
 4   population_density  371 non-null    str
dtypes: str(5)
memory usage: 28.5 KB

In [26]:
import pandas as pd
dataFrame = pd.read_csv('各鄉鎮市區人口密度.csv')

dataFrame.columns = ["統計年", "區域別", "年底人口數", "土地面積", "人口密碼"] #改變欄位名稱
df = dataFrame.drop(index=0)
df

,統計年,區域別,年底人口數,土地面積,人口密碼
1,106,新北市板橋區,551480,23.1373,23835
2,106,新北市三重區,387484,16.317,23747
3,106,新北市中和區,413590,20.144,20532
4,106,新北市永和區,222585,5.7138,38956
5,106,新北市新莊區,416524,19.7383,21102
...,...,...,...,...,...
371,NaN,NaN,NaN,NaN,NaN
372,NaN,說明：1.人口密度係指每單位土地面積內之人口數。,NaN,NaN,NaN
373,NaN,2.96年12月起，我國土地面積增列東沙群島(2.38平方公里)及南沙群島(0.4896平方公里),NaN,NaN,NaN
374,NaN,，由高雄市代管；原金門縣烏坵鄉面積，因重測由2.6平方公里修正為1.2平方公里。,NaN,NaN,NaN
375,NaN,3.104年12月南沙太平島交通基礎整建工程竣工，增加面積0.0149平方公里。,NaN,NaN,NaN

In [36]:
import pandas as pd
dataFrame = pd.read_csv('各鄉鎮市區人口密度.csv')

dataFrame.columns = ['統計年', '區域別', '年底人口數', '土地面積', '人口密度'] #改變欄位名稱
df = dataFrame.drop(index=0) #刪除第一行
df1 = df.dropna() #刪除缺失值
df2 = df1.drop('統計年', axis=1) #刪除'統計年'欄位

df2

        區域別   年底人口數     土地面積   人口密度
1    新北市板橋區  551480  23.1373  23835
2    新北市三重區  387484   16.317  23747
3    新北市中和區  413590   20.144  20532
4    新北市永和區  222585   5.7138  38956
5    新北市新莊區  416524  19.7383  21102
..      ...     ...      ...    ...
366  連江縣北竿鄉    2360      9.9    238
367  連江縣莒光鄉    1624      4.7    346
368  連江縣東引鄉    1352      3.8    356
369    東沙群島      …      2.38     …
370    南沙群島      …    0.5045     …

[370 rows x 4 columns]

In [5]:
import pandas as pd

# 1. 讀取內政部人口密度 CSV 檔案
dataFrame = pd.read_csv('各鄉鎮市區人口密度.csv')

# 2. 重新定義乾淨的欄位名稱（將原本的英文標題替換掉）
dataFrame.columns = ['統計年', '區域別', '年底人口數', '土地面積', '人口密度']

# 3. 刪除 index 為 0 的那列（因為該列包含重複的中文欄位名稱）
df = dataFrame.drop(index=0)

# 4. 移除包含空值（NaN）的行，確保資料基本完整性
df1 = df.dropna()

# 5. 刪除不需要分析的 '統計年' 欄位（axis=1 代表刪除整欄）
df2 = df1.drop('統計年', axis=1)

# 6. 複製一份 DataFrame，避免動到原始資料並防止 SettingWithCopyWarning 警告
df3 = df2.copy()

# 7. 將 '年底人口數' 轉換為數值型態，若有無法轉換的文字（如備註）會先變成 NaN
df3['年底人口數'] = pd.to_numeric(df3['年底人口數'], errors='coerce')

# 8. 再次移除因上一步轉換而產生的 NaN 空值（徹底清除尾端備註列）
df3 = df3.dropna()

# 9. 將各欄位轉換為正確的計算型態（人口數轉整數、面積與密度轉浮點數）
df3['年底人口數'] = df3['年底人口數'].astype(int)
df3['土地面積'] = df3['土地面積'].astype(float)
df3['人口密度'] = df3['人口密度'].astype(float)

# 10. 印出 DataFrame 的詳細資訊（包含欄位名稱、資料型態與非空值數量）
df3.info()

# 11. 在 Jupyter Notebook 中直接顯示清洗完成的精美資料表格
df3

<class 'pandas.DataFrame'>
RangeIndex: 368 entries, 1 to 368
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   區域別     368 non-null    str
 1   年底人口數   368 non-null    int64
 2   土地面積    368 non-null    float64
 3   人口密度    368 non-null    float64
dtypes: float64(2), int64(1), str(1)
memory usage: 18.1 KB

        區域別   年底人口數     土地面積     人口密度
1    新北市板橋區  551480  23.1373  23835.0
2    新北市三重區  387484  16.3170  23747.0
3    新北市中和區  413590  20.1440  20532.0
4    新北市永和區  222585   5.7138  38956.0
5    新北市新莊區  416524  19.7383  21102.0
..      ...     ...      ...      ...
364  金門縣烏坵鄉     685   1.2000    571.0
365  連江縣南竿鄉    7544  10.4000    725.0
366  連江縣北竿鄉    2360   9.9000    238.0
367  連江縣莒光鄉    1624   4.7000    346.0
368  連江縣東引鄉    1352   3.8000    356.0

[368 rows x 4 columns]

In [7]:
dataFrame.columns = ["統計年", "區域別", "年底人口數", "土地面積", "人口密度"] #改變欄位名稱
df = dataFrame.drop(index=0)
# 1. 移除統計年
df2 = df.drop('統計年', axis=1)
df2
# 2. 將「年底人口數」強制轉為數字，像 '…' 這樣的文字會被強制變成 NaN
df2["年底人口數"] = pd.to_numeric(df2["年底人口數"], errors="coerce")
df2
# 3. 這時候再用 dropna()，就能把原本是 '…' 的東沙、南沙群島（以及其他原本就是 NaN 的列）一次清乾淨！
df2 = df2.dropna(subset=["年底人口數"])
df2.info()
# # 4. 最後順利轉換為整數
df2["年底人口數"] = df2["年底人口數"].astype("int64")
df2["土地面積"] = df2["土地面積"].astype("float")
df2["人口密度"] = df2["人口密度"].astype("int64")

df2.info()
df2

<class 'pandas.DataFrame'>
RangeIndex: 368 entries, 1 to 368
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   區域別     368 non-null    str
 1   年底人口數   368 non-null    float64
 2   土地面積    368 non-null    str
 3   人口密度    368 non-null    str
dtypes: float64(1), str(3)
memory usage: 21.9 KB
<class 'pandas.DataFrame'>
RangeIndex: 368 entries, 1 to 368
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   區域別     368 non-null    str
 1   年底人口數   368 non-null    int64
 2   土地面積    368 non-null    float64
 3   人口密度    368 non-null    int64
dtypes: float64(1), int64(2), str(1)
memory usage: 18.1 KB

        區域別   年底人口數     土地面積   人口密度
1    新北市板橋區  551480  23.1373  23835
2    新北市三重區  387484  16.3170  23747
3    新北市中和區  413590  20.1440  20532
4    新北市永和區  222585   5.7138  38956
5    新北市新莊區  416524  19.7383  21102
..      ...     ...      ...    ...
364  金門縣烏坵鄉     685   1.2000    571
365  連江縣南竿鄉    7544  10.4000    725
366  連江縣北竿鄉    2360   9.9000    238
367  連江縣莒光鄉    1624   4.7000    346
368  連江縣東引鄉    1352   3.8000    356

[368 rows x 4 columns]